apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  annotations:
    github.com/project-slug: backstage-lxtxl/node-app
    backstage.io/techdocs-ref: dir:.
  title: '${{ values.name | dump }} / EC2 instance'
  description: 'An example of a Instance Creation.'
spec:
  type: service
  owner: development
  lifecycle: experimental

